import type { Metadata } from "next";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
const jetbrainsMono = localFont({
    src: "./fonts/JetbrainsMono-Light.woff2",
    variable: "--font-jetbrains-mono",
    weight: "100 400",
});

export const metadata: Metadata = {
    title: "Biblioteca",
    description: "Generated by Marco",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} antialiased`}
            style={{ fontFamily: "var(--font-jetbrains-mono), monospace" }}
        >
        {children}
        </body>
        </html>
    );
}
